# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sncheck', '0003_alloweddeviceregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloweddeviceregion',
            name='user_region',
        ),
        migrations.AddField(
            model_name='alloweddeviceregion',
            name='user_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
