# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sncheck', '0004_auto_20181120_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book name')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
