# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('sncheck', '0004_auto_20180525_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumberCheckJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('is_valid', models.NullBooleanField(verbose_name='SN is valid')),
                ('is_region_match', models.NullBooleanField(verbose_name='Region Match')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.AddField(
            model_name='emailfornotifications',
            name='user_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
