# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-20 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sncheck', '0005_auto_20181120_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
