# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sncheck', '0006_delete_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serialnumbercheckjournal',
            options={'permissions': (('can_check_serial_number_list', 'User can check a list of serial numbers'),)},
        ),
    ]
