# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-10 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refurbishmentdevice',
            options={'permissions': (('view_refurbishment_device_list', 'User can view a list of Refurbishment Devices'), ('can_mark_refurbishment_device_as_returned', 'User Can Mark Refurbishment Devices As Returned'))},
        ),
    ]
