# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0002_auto_20201210_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='refurbishment',
            name='prohibited_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='_refurbishment_prohibited_with_+', to='refurbishment.Refurbishment'),
        ),
    ]
