# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0003_refurbishment_prohibited_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='label_date_field_name',
            field=models.CharField(choices=[('prd', 'Production date'), ('ref', 'Refurbish date')], default='prd', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='sku_suffix',
            field=models.CharField(max_length=3, null=True, verbose_name='Suffix for base SKU'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Condition name'),
        ),
    ]
