# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbishment', '0005_auto_20210112_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='label_date_field_name',
            field=models.CharField(choices=[('prd', 'Production date'), ('ref', 'Refurbish date')], max_length=3),
        ),
        migrations.AlterField(
            model_name='condition',
            name='sku_suffix',
            field=models.CharField(max_length=5, null=True, verbose_name='Suffix for base SKU'),
        ),
    ]
