# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-21 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batteryissue',
            unique_together=set([('device_serial_number', 'received_date')]),
        ),
    ]
