# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-24 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0004_auto_20200921_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_number', models.CharField(max_length=20, unique=True, verbose_name='Device Serial Number')),
                ('filling_date', models.DateTimeField(auto_now_add=True, verbose_name='Fill Date')),
                ('purchase_date', models.DateField(blank=True, help_text='Fill purchase date if available', null=True, verbose_name='Purchase Date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_line_issues', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'permissions': (('view_clock_issue_list', 'User can view a list of Clock Issues'),),
            },
        ),
    ]
