# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('technicalguides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
