# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='group',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
