# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200226_1503'),
        ('technicalguides', '0002_auto_20180614_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
