# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0002_guide_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='author',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='device',
        ),
        migrations.AddField(
            model_name='guide',
            name='device',
            field=models.ManyToManyField(to='technicalguides.Device'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 10, 13, 21, 46, 6, 524714, tzinfo=utc)),
        ),
    ]
