# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-12 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0003_guide__device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='_device',
            new_name='new_device',
        ),
    ]
