# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0004_auto_20171014_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default=3, max_length=50),
            preserve_default=False,
        ),
    ]
