# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0005_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('"alert alert-primary"', 'alert alert-primary'), ('alert alert-success', 'alert alert-success'), ('alert alert-danger', 'alert alert-danger'), ('alert alert-warning', 'alert alert-warning'), ('alert alert-info', 'alert alert-info'), ('alert alert-light', 'alert alert-light'), ('alert alert-dark', 'alert alert-dark')], max_length=50),
        ),
    ]
