# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0007_auto_20171014_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('alert alert-primary', 'primary'), ('alert alert-success', 'success'), ('alert alert-danger', 'danger'), ('alert alert-warning', 'warning'), ('alert alert-info', 'info'), ('alert alert-light', 'light'), ('alert alert-dark', 'dark')], max_length=50),
        ),
    ]
