# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0008_auto_20171014_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
