# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0009_guide_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='device',
        ),
        migrations.AddField(
            model_name='guide',
            name='device',
            field=models.ForeignKey(blank=True, default=111, on_delete=django.db.models.deletion.CASCADE, to='technicalguides.Device'),
            preserve_default=False,
        ),
    ]
