# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0010_auto_20171015_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
