# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 20:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('technicalguides', '0011_auto_20171016_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
