# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0013_chessboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboard',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
