# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0014_chessboard_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='group',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
