# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technicalguides', '0015_auto_20171125_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicalguides.Device'),
        ),
    ]
