# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('WordWide', 'WordWide'), ('RU', 'RU'), ('CIS', 'CIS')], max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=50)),
            ],
        ),
    ]
