# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('filling_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('received_date', models.DateField(verbose_name='Received Date')),
                ('conclusion_date', models.DateTimeField(blank=True, null=True, verbose_name='Conclusion Date')),
                ('is_presale', models.BooleanField(verbose_name='It is presale')),
                ('customers_claim', models.CharField(max_length=50, verbose_name='Customers Claim')),
                ('identified_malfunction', models.CharField(max_length=50, verbose_name='Identified Malfunction')),
                ('warranty_card_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of warranty card or receipt')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of warranty card or receipt')),
                ('screen_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of screen')),
                ('defect_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of defect')),
                ('client_name', models.CharField(max_length=50, verbose_name='Client Name')),
                ('seller_name', models.CharField(max_length=50, verbose_name='Seller Name')),
                ('document_type', models.CharField(choices=[('money_back_document', 'Money Back Document'), ('out_of_warranty', 'Out of Warranty'), ('no_fault_found', 'No Fault Found'), ('region_mismatch', 'Region Mismatch')], max_length=100, verbose_name='Type')),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=50, verbose_name='Status')),
                ('comment_of_engineer', models.TextField(blank=True, max_length=140, null=True, verbose_name='Comment of Engineer')),
                ('comment_of_manager', models.TextField(blank=True, max_length=140, null=True, verbose_name='Comment of Manager')),
                ('accepted_or_declined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_or_declined_by', to=settings.AUTH_USER_MODEL, verbose_name='Accepted or declined by')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
