# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('item_en', models.CharField(max_length=20, null=True)),
                ('item_ru', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('protocol_number', models.CharField(max_length=10, null=True, verbose_name='Protocol Number')),
                ('filling_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('received_date', models.DateField(verbose_name='Received Date')),
                ('conclusion_date', models.DateTimeField(blank=True, null=True, verbose_name='Conclusion Date')),
                ('is_presale', models.BooleanField(verbose_name='It is presale')),
                ('customers_claim', models.CharField(max_length=50, verbose_name='Customers Claim')),
                ('identified_malfunction', models.CharField(max_length=50, verbose_name='Identified Malfunction')),
                ('conclusion', models.CharField(max_length=240, null=True, verbose_name='Conclusion')),
                ('warranty_card_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of warranty card')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of receipt')),
                ('screen_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of screen')),
                ('defect_photo', models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of defect')),
                ('client_name', models.CharField(max_length=50, verbose_name='Client Name')),
                ('document_type', models.CharField(choices=[('warranty_rejection', 'Statement of manufacturer warranty rejection'), ('technical_inspection', 'Statement of manufacturer technical inspection'), ('defect_acceptence', 'Statement of  manufacturer defect acceptence')], max_length=100, verbose_name='Type')),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='in_process', max_length=50, verbose_name='Status')),
                ('comment_of_engineer', models.TextField(blank=True, max_length=140, null=True, verbose_name='Comment of Engineer')),
                ('comment_of_manager', models.TextField(blank=True, max_length=140, null=True, verbose_name='Comment of Manager')),
                ('accepted_or_declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_or_declined_by', to=settings.AUTH_USER_MODEL, verbose_name='Accepted or declined by')),
                ('accessories', models.ManyToManyField(to='documents.Accessory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumberPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Device name')),
                ('prefix', models.CharField(max_length=3, verbose_name='Serial Number Prefix')),
            ],
        ),
        migrations.CreateModel(
            name='VisualDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.CharField(max_length=20)),
                ('defect_en', models.CharField(max_length=20, null=True)),
                ('defect_ru', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='visual_defect',
            field=models.ManyToManyField(to='documents.VisualDefect'),
        ),
    ]
