# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='conclusion',
            field=models.TextField(max_length=240, null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='act',
            name='document_type',
            field=models.CharField(choices=[('warranty_rejection', 'Statement of manufacturer warranty rejection'), ('technical_inspection', 'Statement of manufacturer technical inspection'), ('defect_acceptance', 'Statement of  manufacturer defect acceptance')], max_length=100, verbose_name='Type'),
        ),
    ]
