# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumberPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Device name')),
                ('prefix', models.CharField(max_length=3, verbose_name='Serial Number Prefix')),
            ],
        ),
    ]
