# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181112_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessory',
            new_name='ScopeOfSupply',
        ),
        migrations.RemoveField(
            model_name='act',
            name='accessories',
        ),
        migrations.AddField(
            model_name='act',
            name='scope_of_supply',
            field=models.ManyToManyField(blank=True, to='documents.ScopeOfSupply', verbose_name='Scope of Supply'),
        ),
        migrations.AlterField(
            model_name='act',
            name='customers_claim',
            field=models.CharField(max_length=50, verbose_name='Customer Claim'),
        ),
        migrations.AlterField(
            model_name='act',
            name='document_type',
            field=models.CharField(choices=[('warranty_rejection', 'Statement of manufacturer warranty rejection'), ('technical_inspection', 'Statement of manufacturer technical inspection'), ('defect_acceptance', 'Statement of  manufacturer defect acceptance')], max_length=100, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='act',
            name='is_presale',
            field=models.BooleanField(verbose_name='Presale'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('in_process', 'In Process'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='in_process', max_length=50, verbose_name='Satatus'),
        ),
        migrations.AlterField(
            model_name='act',
            name='visual_defect',
            field=models.ManyToManyField(blank=True, to='documents.VisualDefect', verbose_name='Visual (cosmetic) Defects:'),
        ),
    ]
