# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-20 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_serialnumberprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='protocol_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Protocol Number'),
        ),
        migrations.AlterField(
            model_name='act',
            name='accepted_or_declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_or_declined_by', to=settings.AUTH_USER_MODEL, verbose_name='Accepted or declined by'),
        ),
        migrations.AlterField(
            model_name='act',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('in_process', 'In Process'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='in_process', max_length=50, verbose_name='Status'),
        ),
    ]
