# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20181020_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VisualDefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='act',
            name='seller_name',
        ),
        migrations.AlterField(
            model_name='act',
            name='document_type',
            field=models.CharField(choices=[('warranty_rejection', 'Statement of manufacturer warranty rejection'), ('technical_inspection', 'Statement of manufacturer technical inspection'), ('defect_acceptence', 'Statement of  manufacturer defect acceptence')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='act',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of receipt'),
        ),
        migrations.AlterField(
            model_name='act',
            name='warranty_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to=documents.models.upload_path_handler, verbose_name='Photo of warranty card'),
        ),
        migrations.AddField(
            model_name='act',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Accessory'),
        ),
        migrations.AddField(
            model_name='act',
            name='visual_defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.VisualDefect'),
        ),
    ]
