# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20181118_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='comment_of_engineer',
            field=models.TextField(blank=True, max_length=140, null=True, verbose_name='Comments (for PocketBook)'),
        ),
        migrations.AlterField(
            model_name='scopeofsupply',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scopeofsupply',
            name='item_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofsupply',
            name='item_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visualdefect',
            name='defect',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visualdefect',
            name='defect_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visualdefect',
            name='defect_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
