# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181030_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='accessories',
        ),
        migrations.AddField(
            model_name='act',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, to='documents.Accessory'),
        ),
        migrations.RemoveField(
            model_name='act',
            name='visual_defect',
        ),
        migrations.AddField(
            model_name='act',
            name='visual_defect',
            field=models.ManyToManyField(blank=True, null=True, to='documents.VisualDefect'),
        ),
    ]
