# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20181030_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='conclusion',
            field=models.CharField(max_length=50, null=True, verbose_name='Conclusion'),
        ),
    ]
