# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-29 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20190725_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['-filling_date']},
        ),
    ]
