# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20181102_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='conclusion',
            field=models.CharField(max_length=240, null=True, verbose_name='Conclusion'),
        ),
    ]
