# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20181102_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='ru_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
