# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20210127_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeofsupply',
            name='item_ua',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visualdefect',
            name='defect_ua',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
