# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-08 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20210208_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopeofsupply',
            old_name='item_ua',
            new_name='item_uk',
        ),
        migrations.RenameField(
            model_name='visualdefect',
            old_name='defect_ua',
            new_name='defect_uk',
        ),
    ]
