# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='sparepart.Category'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='device.Device'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='sparepart.Manufacturer'),
        ),
    ]
