# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_auto_20200226_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='device.Device'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='sparepart.Supplier'),
        ),
    ]
