# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-27 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200226_1503'),
        ('sparepart', '0004_auto_20200226_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='sparepart.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='device',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='device',
            field=models.ManyToManyField(related_name='spare_parts', to='device.Device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(upload_to='spareparts', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='sparepart.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of spare part'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Purchase price, $'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='size',
            field=models.CharField(max_length=25, verbose_name='Size, millimeters'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='sparepart.Supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='weight',
            field=models.PositiveSmallIntegerField(verbose_name='Weight grams'),
        ),
    ]
