# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0005_auto_20200227_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, upload_to='spareparts', verbose_name='Photo'),
        ),
    ]
