# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-11 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparepart', '0007_auto_20210409_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(max_length=50, validators=['O', 'r', 'd', 'e', 'r', ' ', 'd', 'e', 's', 't', 'i', 'n', 'a', 't', 'i', 'o', 'n'])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='orders')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, verbose_name='Invoice Number')),
                ('invoice_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('received', 'Received')], default='in_process', max_length=20)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('post_service', models.CharField(max_length=50, verbose_name='Delivery Service Name')),
                ('track_number', models.CharField(max_length=50, verbose_name='Track Number')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_supplier', to='sparepart.Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sparepart.Supplier', verbose_name='orders_supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sparepart.OrderSupplier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='sparepart.SparePart'),
        ),
    ]
