# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0008_auto_20210411_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=50, verbose_name='Order destination'),
        ),
        migrations.AlterField(
            model_name='ordersupplier',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
