# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0010_auto_20210419_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupplier',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
