# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0011_auto_20210419_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Part Number'),
        ),
    ]
