# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model_number', models.CharField(max_length=10)),
                ('serial_number_prefix', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='device')),
            ],
        ),
    ]
