# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-26 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20200226_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='serial_number_prefix',
            new_name='sn_prefix',
        ),
    ]
