# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20201217_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Factory'),
        ),
    ]
