# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
    ]
