# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20201225_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(db_index=True, max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('model_number', 'code')]),
        ),
    ]
