# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_auto_20210119_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
