# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_auto_20210120_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='model_name',
            field=models.CharField(max_length=30),
        ),
    ]
